### ISSUE TITLE
"live-streaming" example app is giving throwing application error when activating streaming "Stream"

### ISSUE THREAD

**Issue by mduecker** [daily-demos/examples#65]
Hi daily.co team,
I wanted to try out the [live-streaming](https://github.com/daily-demos/examples/tree/main/custom/live-streaming) example demo at:
https://custom-live-streaming.vercel.app/

When I'm clicking "Stream" in the video UI it's crashing the app:
![image](https://user-images.githubusercontent.com/10739903/149488582-34357dec-a318-45c3-9d20-753674c87d5e.png)

More details on the error, when running it locally:
![image](https://user-images.githubusercontent.com/10739903/149488733-3ea865cc-38ff-42f4-bf34-def589655145.png)

```
Warning: React.jsx: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check your code at LiveStreamingModal.js:58.
    at LiveStreamingModal (webpack-internal:///./components/LiveStreamingModal.js:58:105)
    at Modals (webpack-internal:///../basic-call/components/App/Modals.js:24:104)
```

**Comment by mduecker** [comment]
It's the `<Button/>` components passed to the `actions` prop `<Modal/>`, if I just pass an empty array there it works:
https://github.com/daily-demos/examples/blob/main/custom/live-streaming/components/LiveStreamingModal.js#L57
```
<Modal
...
 actions={[])
...
>
```

**Comment by harshithpabbati** [comment]
I am closing this issue, as it's fixed!
